# Generated by Django 4.2.6 on 2023-10-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('octo_payment_uuid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUCCEEDED', 'Succeeded'), ('CANCELED', 'Canceled')], default='CREATED', max_length=32)),
                ('payment_method', models.CharField(max_length=128)),
                ('tag', models.IntegerField(choices=[(0, 'Refill'), (1, 'Subscription'), (2, 'Premium')])),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transfer_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
